version: "3"

services:
    # quiz-server:
    #     image: ccns/quiz-server:latest
    #     ports:
    #         - "8080:8080"
    postgres:
        image: "postgres"
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=${PG_DBNAME}
            - POSTGRES_USER=${PG_USERNAME}
            - POSTGRES_PASSWORD=${PG_PASSWORD}